services:
  #Our postgreSQL database
  db:
    #Using latest postgreSQL image
    image:  postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: root

  #Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080